### ISSUE TITLE
Custom styles

### ISSUE THREAD

**Issue by IrvingArmenta** [edwardfhsiao/react-inputs-validation#5]
Question: 
**What is the proper way to add my own styles or modify the ones that are added?**

**Comment by edwardfhsiao** [comment]
Can you provide an example that you wish to modify?

**Comment by IrvingArmenta** [comment]
This is what I was looking for, thank you.

**Comment by MRMTC** [comment]
Hi Guys :)

Firstly, thanks for the great library!  Its really helped me to get some validations implemented on my forms.  I was trying to update the width of the "Textbox" and "Select" components so that they don't stretch across the entire screen as seen below:

![image](https://user-images.githubusercontent.com/26508189/45590000-08159100-b930-11e8-876f-d0d8e7ccf74e.png)

Can you please guide me on where the best place is to update the width/CSS so that for example the two elements can sit side by side?

Thanks.

**Comment by MRMTC** [comment]
So I got the width of each element to scale down using the CSS elements seen below (including removing one of the borders), but I can't get them to be inline with one another?  Do you guys have any suggestions with respect to that?

`.react-inputs-validation__textbox__wrapper___3tnXv{
	width: 15em !important;
}

.react-inputs-validation__select__wrapper___1B4OH{
	width: 15em !important;
}

.react-inputs-validation__msg___pxv8o .react-inputs-validation__error___2aXSp {
    padding: 0% !important;
    position: relative;
    border: 0px solid #e5e5e5 !important;
    box-shadow: inset 0 1px 1px rgba(0,0,0,0.075);	
}

.react-inputs-validation__select__container___3jgUR {
    padding: 0% !important;
    position: relative;
    border: 0px solid #e5e5e5 !important;
    /*box-shadow: inset 0 1px 1px rgba(0,0,0,0.075);*/
}`

![image](https://user-images.githubusercontent.com/26508189/45600157-59895300-b9f8-11e8-9b22-5238fc1abf03.png)

**Comment by edwardfhsiao** [comment]
why don't you wrap Components inside a div? So that you can manipulate the with of the Textbox by manipulating its parent


maybe something like this
https://codesandbox.io/s/mo6y614v88

**Comment by MRMTC** [comment]
Thanks @edwardfhsiao :)  I was actually looking at doing something like this with the bootstrap libraries as well - I got to the same point i.e. where the boxes were centered underneath one another.  Your way is simpler though, so I have adopted that :)

Is there a way to put the "input" and "dropdown" boxes next to each other?  Something like:
"Place your name here ^-^"      "US    ⌄"

Instead of the current:
"Place your name here ^-^"
"US    ⌄"

It seems like there is a "break" between the two components that I can't get rid of?

**Comment by edwardfhsiao** [comment]
you want dropdown to be inside the input or just line up next to the input ?

**Comment by MRMTC** [comment]
Hi @edwardfhsiao,

Apologies for the confusion on my end.  I would like to get them to align to one another as in the "mock" view below that I edited from your code sandbox above:
![image](https://user-images.githubusercontent.com/26508189/45605551-14880f80-ba3e-11e8-848e-cb617eab1557.png)

**Comment by edwardfhsiao** [comment]
https://codesandbox.io/s/mo6y614v88

**Comment by edwardfhsiao** [comment]
@MRMTC my pleasure
