### ISSUE TITLE
Custom message for empty textbox

### ISSUE THREAD

**Issue by cipriancx** [edwardfhsiao/react-inputs-validation#7]
Hello,

For Textbox: it is possible to add a msgOnEmpty property to allow a custom message(when input is required and empty) instead of Msg.empty(nameText) ? or a way to override the Message object.

Thank you!

**Comment by edwardfhsiao** [comment]
hi, one way to do it is to provide ```msgOnError```, but it does not specifically for error on empty only. Because it has so many types of error, the lib gets huge when trying to provide all kinds of the custom error message.

```js
                validationOption={{
                  name: 'Name', //Optional.[String].Default: "". To display in the Error message. i.e Please enter your ${name}.
                  check: true, //Optional.[Bool].Default: true. To determin if you need to validate.
                  required: true, //Optional.[Bool].Default: true. To determin if it is a required field.
                  msgOnError: '???'
                }}
```

The other way is that try to validate yourself. Check this out https://codesandbox.io/s/pjom8r78x7

**Comment by edwardfhsiao** [comment]
please check v1.1.1
